os: linux
dist: focal

branches:
  only:
    - master
    - prod

language: java
jdk:
  - openjdk13

cache:
  directories:
    - "$HOME/.m2"

install: echo "Skipping installation..."

script:
  - mvn clean deploy -DskipTests=true --settings .ci/settings.xml

notifications:
  email: false
  slack:
    rooms:
      - mydnacodes:2aXZWSXfUxDEKC64jl9rugZe#travis-ci
    on_success: always
    on_failure: always
    template:
      - "Repository %{repository_slug} %{result} build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch %{branch}."
      - "Commit author: %{author}"
      - "Commit message: %{commit_message}"
      - "Execution time: %{duration}"
      - "Message: %{message}"